# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres  
  password: postgres

development:
  <<: *default
  database: gabi_project_backend_development

test:
  <<: *default
  database: gabi_project_backend_test

production:
  primary: &primary_production
    <<: *default
    database: gabi_project_backend_production
    username: gabi_project_backend
    password: <%= ENV["GABI_PROJECT_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: gabi_project_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: gabi_project_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: gabi_project_backend_production_cable
    migrations_paths: db/cable_migrate
